modules:
  Create-Links: true
  Create-StartupLinks: true
  Install-NodePackages: false
  Install-PS-Modules: false
  Install-CodeExtensions: true
  Manage-Services: true
  Update-Registry: false
  Update-RegistryKeys: false
  Process-Programs: true
